### ISSUE TITLE
rustless.org domain name expired

### ISSUE THREAD

**Issue by anna-liao** [rustless/rustless#78]
http://rustless.org/

NOTICE: This domain name expired on 10/5/2016 and is pending renewal or deletion.

**Comment by AmarOk1412** [comment]
I confirm, the description is not up to date. (btw, you can see the previous site with http://web.archive.org/web/20160424041045/http://rustless.org/)

**Comment by djmitche** [comment]
This is now squatted by malware.  I assume this project is dead?

**Comment by s-panferov** [comment]
I've removed the link to the site. I've decided not to renew the domain, because it costs too much for me without any profit. `README.md` is enough.

About status of the project: Rustless has a full set of features for now. I’m waiting until Rust’s async story will be stabilized. Also we need full async support in Hyper and Iron to continue improvements of the project.

**Comment by djmitche** [comment]
Thanks for the update!
